version: "3.8"

networks:
   monitoring:
     driver: bridge

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    networks:
     - monitoring
    depends_on:
     - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
     - 6379:6379
    networks:
     - monitoring
    
  notes-app:
    image: notes-app:latest
    build:
      context: ./notes-app
      dockerfile: Dockerfile
    container_name: notes-app
    ports:
      - 8000:8000
    networks:
      - monitoring
    volumes:
      - ./notes-app:/app

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - prometheus_data:/prometheus
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
    - cadvisor
    networks:
      - monitoring
  
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./data/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./data/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - monitoring
   
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
     - monitoring
    ports:
     - 80:80
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - /var/log/nginx:/var/log/nginx  

  loki: 
    image: grafana/loki:latest
    container_name: loki
    ports:
      - 3100:3100
    networks:
      - monitoring
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yml
  
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
     - ./promtail-config.yaml:/etc/promtail/promtail-config.yml
     - /var/log:/var/log
     - /var/log/nginx:/var/log/nginx  
    networks:
     - monitoring  
